### ISSUE TITLE
SecurityPolicyDsc: Converting to new CI pipeline

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SecurityPolicyDsc#143]
Work need to be done to convert this repository to use the new CI pipeline.

https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/

**Comment by johlju** [comment]
These PR's should be merged which will help with the conversion process: 
https://github.com/dsccommunity/SecurityPolicyDsc/pull/139
https://github.com/dsccommunity/SecurityPolicyDsc/pull/138
https://github.com/dsccommunity/SecurityPolicyDsc/pull/137

**Comment by X-Guardian** [comment]
Hi @johlju,  if you can start merging in the documentation update PRs, I'll convert this module to the new CI pipeline.

**Comment by johlju** [comment]
Done!

**Comment by X-Guardian** [comment]
Cheers! have all the latest changes we have been making to the pipeline been applied to the Sampler template?

**Comment by X-Guardian** [comment]
Hi @johlju, I can't update the Git tags, as I have no write permissions to this repo. Do you want to do that stage, or give me permissions to do so?

**Comment by johlju** [comment]
> Cheers! have all the latest changes we have been making to the pipeline been applied to the Sampler template?

Not all no. :/

**Comment by johlju** [comment]
> Hi @johlju, I can't update the Git tags, as I have no write permissions to this repo. Do you want to do that stage, or give me permissions to do so?

Let's ping @gaelcolas on Slack so you get access everywhere. I think I can give you permission to the repo though.

**Comment by X-Guardian** [comment]
OK, I'm going to take the azure-pipelines.yml from ActiveDirectoryDsc and use that then.

**Comment by johlju** [comment]
Yes do that it is the fastest

**Comment by johlju** [comment]
@X-Guardian You should gotten an invite to the repo now.

**Comment by X-Guardian** [comment]
Yep cheers, I can see 'Settings' on the repo now.
